# ruff.toml
select = [
  "E",   # PEP 8 ошибки (Flake8)
  "F",   # Ошибки синтаксиса (PyFlakes)
  "W",   # Предупреждения PEP 8
  "I",   # isort (сортировка импортов)
  "UP",  # PyUpgrade (обновление устаревшего синтаксиса)
]
ignore = ["E501"]  # Игнорировать длинные строки (или любые другие правила)

# Автоматическое исправление
fixable = ["I", "UP", "E", "W"]
unfixable = ["F"]

# Форматирование
[format]
docstring-code-format = true