name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # 3.13 пока не поддерживается

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.2

    - name: Configure Poetry to use in-project virtualenv
      run: poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: poetry install --no-root --sync

    - name: Run Ruff linter
      run: poetry run ruff check .

    - name: Check formatting (optional)
      run: poetry run ruff format --check .

    - name: Placeholder for tests
      run: echo "✅ No tests defined yet"
